import Link from "next/link";
import {Activity,ArrowRight,CheckCircle2,FolderKanban,ShieldAlert,Users} from "lucide-react";
import {Header} from "@/components/sidebar";
import {Status} from "@/components/status";
import {createClient} from "@/lib/supabase/server";
import type {Project,ProjectGroup} from "@/lib/types";

export default async function Dashboard(){const supabase=await createClient();const {data,error}=await supabase.from("projects").select("*,customers(name)").eq("archived",false).order("updated_at",{ascending:false});if(error)throw new Error(error.message);const projects=(data||[]) as Project[],groupOf=(project:Project):ProjectGroup=>project.project_group||(project.customer_id?"customer_project":"portfolio"),portfolio=projects.filter(project=>groupOf(project)==="portfolio"),customers=projects.filter(project=>groupOf(project)==="customer_project"),stats=[{label:"Toplam proje",value:projects.length,detail:`${portfolio.length} kişisel · ${customers.length} müşteri`,icon:FolderKanban,tone:"blue"},{label:"Aktif",value:countStatus(projects,"aktif"),detail:"Canlı ve operasyonda",icon:Activity,tone:"green"},{label:"Geliştiriliyor",value:countStatus(projects,"gelistiriliyor"),detail:"Devam eden çalışmalar",icon:Users,tone:"violet"},{label:"Kritik",value:projects.filter(project=>project.critical||project.health_status==="critical").length,detail:"İlgi gerektiren kayıt",icon:ShieldAlert,tone:"red"}] as const;return <><Header title="Dashboard" description="MK Digital Systems proje operasyon görünümü."/><div className="space-y-5 p-4 sm:p-5 lg:p-6"><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{stats.map(({label,value,detail,icon:Icon,tone})=><div className="panel-surface relative overflow-hidden p-4" key={label}><div className={`absolute inset-y-0 left-0 w-1 stat-${tone}`}/><div className="flex items-start justify-between gap-3"><div><div className="text-2xl font-black tracking-tight text-slate-950">{value}</div><div className="mt-0.5 text-sm font-bold text-slate-700">{label}</div><div className="mt-1 text-[11px] text-slate-500">{detail}</div></div><div className={`stat-icon stat-icon-${tone}`}><Icon size={17}/></div></div></div>)}</section>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.55fr)_minmax(300px,.7fr)]"><section className="panel-surface overflow-hidden"><div className="flex items-center justify-between border-b border-slate-200 px-4 py-3"><div><h2 className="text-sm font-bold text-slate-900">Son Güncellenen Projeler</h2><p className="mt-0.5 text-xs text-slate-500">En son hareket gören proje kayıtları</p></div><Link href="/projects" className="inline-flex items-center gap-1 text-xs font-bold text-blue-600 hover:text-blue-700">Tüm projeler<ArrowRight size={14}/></Link></div>{projects.length?<div className="divide-y divide-slate-100">{projects.slice(0,8).map(project=><Link href={`/projects/${project.id}`} className="group flex items-center justify-between gap-4 px-4 py-3 transition hover:bg-blue-50/60" key={project.id}><div className="min-w-0"><div className="truncate text-sm font-bold text-slate-900 group-hover:text-blue-700">{project.name}</div>{project.short_description&&<div className="mt-0.5 truncate text-xs text-slate-500">({project.short_description})</div>}<div className="mt-1 text-[11px] font-medium text-slate-400">{groupOf(project)==="portfolio"?"Kişisel Proje":project.customers?.name||"Müşteri Projesi"} · {new Date(project.updated_at).toLocaleDateString("tr-TR")}</div></div><div className="flex shrink-0 items-center gap-2"><Status value={project.status}/><ArrowRight size={15} className="text-slate-300 group-hover:text-blue-600"/></div></Link>)}</div>:<Empty text="Henüz proje bulunmuyor."/>}</section>
      <div className="space-y-5"><GroupSummary title="Kişisel Projeler" projects={portfolio} href="/projects"/><GroupSummary title="Müşteri Projeleri" projects={customers} href="/projects"/><section className="rounded-xl bg-[#0b1630] p-4 text-white"><div className="flex items-center gap-2 text-sm font-bold"><CheckCircle2 size={17} className="text-blue-400"/>Hızlı Erişim</div><div className="mt-3 grid gap-2"><QuickLink href="/projects/new" label="Yeni proje oluştur"/><QuickLink href="/domains" label="Domain durumlarını aç"/></div></section></div></div>
  </div></>}

function GroupSummary({title,projects,href}:{title:string;projects:Project[];href:string}){return <section className="panel-surface p-4"><div className="flex items-center justify-between"><h2 className="text-sm font-bold text-slate-800">{title}</h2><Link href={href} className="text-slate-400 hover:text-blue-600"><ArrowRight size={15}/></Link></div><div className="mt-3 grid grid-cols-3 divide-x divide-slate-200 rounded-lg bg-slate-50 py-2.5 text-center"><MiniStat label="Toplam" value={projects.length}/><MiniStat label="Aktif" value={countStatus(projects,"aktif")}/><MiniStat label="Devam" value={countStatus(projects,"gelistiriliyor")}/></div></section>}
function MiniStat({label,value}:{label:string;value:number}){return <div><div className="font-black text-slate-900">{value}</div><div className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">{label}</div></div>}
function QuickLink({href,label}:{href:string;label:string}){return <Link href={href} className="flex items-center justify-between rounded-lg border border-white/10 bg-white/5 px-3 py-2 text-xs font-semibold text-slate-200 transition hover:border-blue-500/40 hover:bg-blue-500/10 hover:text-white">{label}<ArrowRight size={14}/></Link>}
function Empty({text}:{text:string}){return <div className="p-10 text-center text-sm text-slate-500">{text}</div>}
function countStatus(projects:Project[],status:string){return projects.filter(project=>project.status===status).length}
