"use server";
import {z} from "zod";import {revalidatePath} from "next/cache";import {createClient} from "@/lib/supabase/server";
const text=z.string().trim().min(1);const amount=z.coerce.number().positive();async function db(){const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Oturum gerekli");return {supabase,user}}const val=(fd:FormData,k:string)=>String(fd.get(k)||"");
export async function saveIncome(fd:FormData){const r={amount:amount.parse(val(fd,"amount")),income_date:z.string().date().parse(val(fd,"date")),category_id:val(fd,"category_id")||null,source:val(fd,"source"),description:val(fd,"description"),recurring:fd.get("recurring")==="on"};const {supabase,user}=await db(),id=val(fd,"id");const {error}=id?await supabase.from("finance_income").update(r).eq("id",z.string().uuid().parse(id)):await supabase.from("finance_income").insert({...r,created_by:user.id});if(error)throw new Error(error.message);revalidatePath("/finance")}
export async function saveExpense(fd:FormData){const r={amount:amount.parse(val(fd,"amount")),expense_date:z.string().date().parse(val(fd,"date")),category_id:val(fd,"category_id")||null,payment_method:val(fd,"payment_method"),description:val(fd,"description"),recurring:fd.get("recurring")==="on"};const {supabase,user}=await db(),id=val(fd,"id");const {error}=id?await supabase.from("finance_expenses").update(r).eq("id",z.string().uuid().parse(id)):await supabase.from("finance_expenses").insert({...r,created_by:user.id});if(error)throw new Error(error.message);revalidatePath("/finance")}
export async function saveInstallment(fd:FormData){const count=z.coerce.number().int().positive().parse(val(fd,"count")),total=amount.parse(val(fd,"total")),start=z.string().date().parse(val(fd,"start_date"));const r={name:text.parse(val(fd,"name")),total_amount:total,installment_count:count,installment_amount:Number((total/count).toFixed(2)),paid_installment_count:0,start_date:start,next_payment_date:start,payment_day:new Date(start+"T12:00:00").getDate(),payment_method:val(fd,"payment_method"),description:val(fd,"description")};const {supabase,user}=await db();const {error}=await supabase.from("finance_installments").insert({...r,created_by:user.id});if(error)throw new Error(error.message);revalidatePath("/finance")}
export async function saveCategory(fd:FormData){const r=z.object({name:text.max(60),type:z.enum(["income","expense"])}).parse({name:val(fd,"name"),type:val(fd,"type")});const {supabase,user}=await db();const {error}=await supabase.from("finance_categories").insert({...r,created_by:user.id});if(error)throw new Error(error.message);revalidatePath("/finance")}
export async function deleteFinanceRecord(fd:FormData){const table=z.enum(["finance_income","finance_expenses","finance_installments"]).parse(val(fd,"table")),id=z.string().uuid().parse(val(fd,"id"));const {supabase}=await db();const {error}=await supabase.from(table).delete().eq("id",id);if(error)throw new Error(error.message);revalidatePath("/finance")}
export async function payInstallment(fd:FormData){const id=z.string().uuid().parse(val(fd,"id"));const {supabase}=await db();const {error}=await supabase.rpc("pay_finance_installment",{p_installment_id:id,p_payment_date:new Date().toISOString().slice(0,10)});if(error)throw new Error(error.message);revalidatePath("/finance")}
export async function createProject(fd:FormData){const r=z.object({name:text.max(160),short_name:z.string().max(40).optional(),description:z.string().max(2000).optional(),customer_id:z.string().uuid().nullable(),status:z.enum(["fikir","gelistiriliyor","test","aktif","bakim","beklemede","tamamlandi","arsiv"])}).parse({name:val(fd,"name"),short_name:val(fd,"short_name"),description:val(fd,"description"),customer_id:val(fd,"customer_id")||null,status:val(fd,"status")});const {supabase,user}=await db();const {error}=await supabase.from("projects").insert({...r,created_by:user.id});if(error)throw new Error(error.message);revalidatePath("/projects")}
