"use server";
import {revalidatePath} from "next/cache";
import {createClient} from "@/lib/supabase/server";
import {z} from "zod";

const id=z.string().uuid(),date=z.string().date(),amount=z.coerce.number().positive(),text=z.string().trim().min(1).max(500);
const value=(fd:FormData,key:string)=>String(fd.get(key)||"");
async function auth(){const supabase=await createClient(),{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Oturum gerekli");return {supabase,user};}
export async function saveWorkAdvance(fd:FormData){const record={advance_date:date.parse(value(fd,"date")),amount:amount.parse(value(fd,"amount")),description:z.string().trim().max(500).parse(value(fd,"description"))||null},{supabase,user}=await auth(),recordId=value(fd,"id");const result=recordId?await supabase.from("work_advances").update(record).eq("id",id.parse(recordId)):await supabase.from("work_advances").insert({...record,created_by:user.id});if(result.error)throw new Error(result.error.message);revalidatePath("/work-advance");}
export async function deleteWorkAdvance(fd:FormData){const {supabase}=await auth(),{error}=await supabase.from("work_advances").delete().eq("id",id.parse(value(fd,"id")));if(error)throw new Error(error.message);revalidatePath("/work-advance");}
export async function saveWorkExpense(fd:FormData){const record={expense_date:date.parse(value(fd,"date")),amount:amount.parse(value(fd,"amount")),description:text.parse(value(fd,"description"))},{supabase,user}=await auth(),recordId=value(fd,"id");if(recordId){const {error}=await supabase.from("work_advance_expenses").update(record).eq("id",id.parse(recordId));if(error)throw new Error(error.message);revalidatePath("/work-advance");return recordId;}const {data,error}=await supabase.from("work_advance_expenses").insert({...record,created_by:user.id}).select("id").single();if(error)throw new Error(error.message);revalidatePath("/work-advance");return data.id as string;}
export async function deleteWorkExpense(fd:FormData){const expenseId=id.parse(value(fd,"id")),{supabase}=await auth();const {data:receipts}=await supabase.from("work_advance_receipts").select("file_path").eq("expense_id",expenseId);if(receipts?.length){const {error}=await supabase.storage.from("work-advance-receipts").remove(receipts.map(x=>x.file_path));if(error)throw new Error(error.message);}const {error}=await supabase.from("work_advance_expenses").delete().eq("id",expenseId);if(error)throw new Error(error.message);revalidatePath("/work-advance");}
export async function addWorkReceipts(expenseId:string,paths:string[]){const parsedId=id.parse(expenseId),clean=z.array(z.string().min(1).max(500)).max(10).parse(paths),{supabase,user}=await auth();const {data:expense}=await supabase.from("work_advance_expenses").select("id").eq("id",parsedId).single();if(!expense)throw new Error("Harcama bulunamadı");const {error}=await supabase.from("work_advance_receipts").insert(clean.map(file_path=>({expense_id:parsedId,file_path,created_by:user.id})));if(error)throw new Error(error.message);revalidatePath("/work-advance");}
export async function deleteWorkReceipt(receiptId:string){const {supabase}=await auth(),{data}=await supabase.from("work_advance_receipts").select("file_path").eq("id",id.parse(receiptId)).single();if(!data)throw new Error("Fiş bulunamadı");const {error:storageError}=await supabase.storage.from("work-advance-receipts").remove([data.file_path]);if(storageError)throw new Error(storageError.message);const {error}=await supabase.from("work_advance_receipts").delete().eq("id",receiptId);if(error)throw new Error(error.message);revalidatePath("/work-advance");}
