"use client";
import {ArrowLeft,ChevronRight,Folder,FolderKanban,FolderPlus,Pencil,Search,Trash2,UserRound,UsersRound} from "lucide-react";
import {useRouter} from "next/navigation";
import {useMemo,useState} from "react";
import {createProjectCategory,deleteProjectCategory,renameProjectCategory} from "@/app/actions";
import type {Project,ProjectCategoryNode,ProjectGroup} from "@/lib/types";
import {Status} from "./status";
const groupLabels:Record<ProjectGroup,string>={portfolio:"Kişisel Projeler",customer_project:"Müşteri Projeleri"};
export function ProjectTable({projects,categories,emptyText="Henüz proje bulunmuyor."}:{projects:Project[];categories:ProjectCategoryNode[];emptyText?:string}){
 const router=useRouter(),[group,setGroup]=useState<ProjectGroup|null>(null),[currentId,setCurrentId]=useState<string|null>(null),[query,setQuery]=useState("");
 const byId=useMemo(()=>new Map(categories.map(x=>[x.id,x])),[categories]),current=currentId?byId.get(currentId)||null:null;
 const children=useMemo(()=>categories.filter(x=>x.project_group===group&&x.parent_id===currentId).sort(sortNodes),[categories,group,currentId]);
 const path=useMemo(()=>{const result:ProjectCategoryNode[]=[];let item=current;while(item){result.unshift(item);item=item.parent_id?byId.get(item.parent_id)||null:null}return result},[current,byId]);
 const descendants=useMemo(()=>currentId?descendantIds(currentId,categories):new Set(categories.filter(x=>x.project_group===group).map(x=>x.id)),[currentId,categories,group]);
 const branchProjects=projects.filter(x=>x.project_category_id&&descendants.has(x.project_category_id)),directProjects=projects.filter(x=>x.project_category_id===currentId),term=query.trim().toLocaleLowerCase("tr");
 const searchProjects=term?branchProjects.filter(x=>`${x.name} ${x.short_description||""} ${x.customers?.name||""}`.toLocaleLowerCase("tr").includes(term)):[],searchCategories=term?categories.filter(x=>descendants.has(x.id)&&x.id!==currentId&&x.name.toLocaleLowerCase("tr").includes(term)):[];
 function chooseGroup(value:ProjectGroup){setGroup(value);setCurrentId(null);setQuery("")}function openCategory(id:string){setCurrentId(id);setQuery("")}function goBack(){if(!current){setGroup(null);return}setCurrentId(current.parent_id);setQuery("")}
 if(!group)return <div className="grid gap-4 md:grid-cols-2"><GroupChoice icon={UserRound} label="Kişisel Projeler" count={projects.filter(x=>projectGroup(x)==="portfolio").length} onClick={()=>chooseGroup("portfolio")}/><GroupChoice icon={UsersRound} label="Müşteri Projeleri" count={projects.filter(x=>projectGroup(x)==="customer_project").length} onClick={()=>chooseGroup("customer_project")}/></div>;
 return <div className="space-y-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-2 text-sm"><button type="button" onClick={goBack} className="btn shrink-0"><ArrowLeft size={16}/>Geri</button><nav className="flex min-w-0 items-center gap-1 overflow-x-auto whitespace-nowrap" aria-label="Kategori yolu"><button type="button" onClick={()=>{setCurrentId(null);setQuery("")}} className="font-bold text-blue-700 hover:underline">{groupLabels[group]}</button>{path.map(x=><span className="flex items-center gap-1" key={x.id}><ChevronRight size={14} className="text-slate-400"/><button type="button" onClick={()=>openCategory(x.id)} className="font-semibold text-slate-700 hover:text-blue-700 hover:underline">{x.name}</button></span>)}</nav></div><label className="flex min-h-10 items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 sm:w-72"><Search size={16} className="text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Bu dalda ara..." className="w-full bg-transparent py-2 text-sm outline-none"/></label></div>
 {term?<SearchResults categories={searchCategories} projects={searchProjects} onCategory={openCategory} onProject={id=>router.push(`/projects/${id}`)}/>:children.length?<div className="panel-surface divide-y divide-slate-100 overflow-hidden">{children.map(x=><CategoryRow key={x.id} category={x} count={countProjects(x.id,projects,categories)} onClick={()=>openCategory(x.id)}/>)}</div>:<ProjectRows projects={directProjects} emptyText={emptyText} onOpen={id=>router.push(`/projects/${id}`)}/>} {current&&<CategoryTools category={current} childCount={children.length} projectCount={directProjects.length}/>}</div>;
}
function GroupChoice({icon:Icon,label,count,onClick}:{icon:typeof UserRound;label:string;count:number;onClick:()=>void}){return <button type="button" onClick={onClick} className="group flex min-h-40 items-center gap-5 rounded-2xl border border-slate-200 bg-white p-6 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-blue-300 hover:shadow-md"><span className="grid h-16 w-16 shrink-0 place-items-center rounded-2xl bg-blue-600 text-white"><Icon size={30}/></span><span className="min-w-0 flex-1"><span className="block text-xl font-black text-slate-950">{label}</span><span className="mt-1 block text-sm text-slate-500">{count} proje kaydı</span></span><ChevronRight className="text-slate-400 transition group-hover:translate-x-1 group-hover:text-blue-600"/></button>}
function CategoryRow({category,count,onClick}:{category:ProjectCategoryNode;count:number;onClick:()=>void}){return <button type="button" onClick={onClick} className="group flex w-full items-center gap-3 px-4 py-4 text-left transition hover:bg-blue-50/60"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-amber-50 text-amber-600"><Folder size={21} fill="currentColor"/></span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-bold text-slate-900 group-hover:text-blue-700">{category.name}</span><span className="mt-0.5 block text-xs text-slate-500">{count} proje</span></span><ChevronRight size={19} className="text-slate-400"/></button>}
function ProjectRows({projects,emptyText,onOpen}:{projects:Project[];emptyText:string;onOpen:(id:string)=>void}){return <div className="panel-surface divide-y divide-slate-100 overflow-hidden">{projects.length?projects.map(x=><button type="button" key={x.id} onClick={()=>onOpen(x.id)} className="group flex w-full items-center gap-3 px-4 py-3 text-left transition hover:bg-blue-50/60"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-slate-100 text-slate-500"><FolderKanban size={17}/></span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-bold text-slate-900 group-hover:text-blue-700">{x.name}</span>{x.short_description&&<span className="mt-0.5 block truncate text-xs text-slate-500">{x.short_description}</span>}</span><Status value={x.status}/><ChevronRight size={18} className="shrink-0 text-slate-400"/></button>):<div className="p-10 text-center text-sm text-slate-500">{emptyText}</div>}</div>}
function SearchResults({categories,projects,onCategory,onProject}:{categories:ProjectCategoryNode[];projects:Project[];onCategory:(id:string)=>void;onProject:(id:string)=>void}){return <div className="space-y-3">{categories.length>0&&<div className="panel-surface divide-y divide-slate-100 overflow-hidden">{categories.map(x=><CategoryRow key={x.id} category={x} count={0} onClick={()=>onCategory(x.id)}/>)}</div>}<ProjectRows projects={projects} emptyText={categories.length?"Eşleşen proje bulunamadı.":"Bu dalda eşleşen kategori veya proje bulunamadı."} onOpen={onProject}/></div>}
function CategoryTools({category,childCount,projectCount}:{category:ProjectCategoryNode;childCount:number;projectCount:number}){return <details className="panel-surface p-4"><summary className="flex cursor-pointer list-none items-center gap-2 text-sm font-bold text-slate-700"><FolderPlus size={17}/>Alt kategori yönetimi</summary><div className="mt-4 grid gap-3 lg:grid-cols-3"><form action={createProjectCategory} className="flex gap-2"><input type="hidden" name="parent_id" value={category.id}/><input required maxLength={80} name="name" className="field" placeholder="Yeni alt kategori"/><button className="btn btn-primary shrink-0"><FolderPlus size={15}/>Ekle</button></form>{!category.system_key&&<><form action={renameProjectCategory} className="flex gap-2"><input type="hidden" name="category_id" value={category.id}/><input required maxLength={80} name="name" defaultValue={category.name} className="field"/><button className="btn shrink-0"><Pencil size={15}/>Kaydet</button></form><form action={deleteProjectCategory}><input type="hidden" name="category_id" value={category.id}/><button disabled={Boolean(childCount||projectCount)} className="btn min-h-10 text-red-600 disabled:cursor-not-allowed disabled:opacity-40"><Trash2 size={15}/>Kategoriyi sil</button></form></>}</div>{!category.system_key&&Boolean(childCount||projectCount)&&<p className="mt-3 text-xs text-amber-700">Bu kategori boş olmadığı için silinemez.</p>}</details>}
function projectGroup(x:Project):ProjectGroup{return x.project_group||(x.customer_id?"customer_project":"portfolio")}function sortNodes(a:ProjectCategoryNode,b:ProjectCategoryNode){return a.sort_order-b.sort_order||a.name.localeCompare(b.name,"tr")}
function descendantIds(rootId:string,categories:ProjectCategoryNode[]){const result=new Set<string>([rootId]);let changed=true;while(changed){changed=false;for(const x of categories)if(x.parent_id&&result.has(x.parent_id)&&!result.has(x.id)){result.add(x.id);changed=true}}return result}function countProjects(id:string,projects:Project[],categories:ProjectCategoryNode[]){const ids=descendantIds(id,categories);return projects.filter(x=>x.project_category_id&&ids.has(x.project_category_id)).length}
