"use client";

import Link from "next/link";
import Image from "next/image";
import {usePathname,useRouter} from "next/navigation";
import {useEffect,useState} from "react";
import {BriefcaseBusiness,FolderKanban,Globe2,LayoutDashboard,Loader2,LogOut,Menu,Settings,Users,WalletCards,X} from "lucide-react";
import {toast} from "sonner";
import {createClient} from "@/lib/supabase/client";

type NavItem={href:string;label:string;icon?:typeof LayoutDashboard;groupStart?:boolean;children?:readonly {href:string;label:string}[]};
const navigation:readonly NavItem[]=[{href:"/dashboard",label:"Panel",icon:LayoutDashboard},{href:"/projects",label:"Projeler",icon:FolderKanban},{href:"/customers",label:"Müşteriler",icon:Users},{href:"/domains",label:"Domainler",icon:Globe2},{href:"/settings",label:"Ayarlar",icon:Settings},{href:"/finance",label:"Kişisel Finans",icon:WalletCards,groupStart:true,children:[{href:"/finance",label:"Genel Bakış"},{href:"/finance/income",label:"Gelirler"},{href:"/finance/expenses",label:"Giderler"},{href:"/finance/installments",label:"Taksitler"},{href:"/finance/cash",label:"Kasa"},{href:"/finance/history",label:"Geçmiş / İstatistikler"}]},{href:"/work-advance",label:"İş Avansı",icon:BriefcaseBusiness}];

function Navigation({pathname,onNavigate}:{pathname:string;onNavigate?:()=>void}){return <nav className="flex-1 overflow-y-auto px-3 py-4">{navigation.map(item=><div key={item.href}>{item.groupStart&&<div className="mx-2 my-4 border-t border-white/8"/>}<NavLink item={item} pathname={pathname} onNavigate={onNavigate}/>{item.children&&<div className="relative ml-5 mt-1 border-l border-white/10 pl-3">{item.children.map(child=><Link onClick={onNavigate} key={child.href} href={child.href} className={`block rounded-md px-2.5 py-1.5 text-[11px] font-medium transition ${pathname===child.href?"bg-blue-500/15 text-blue-300":"text-slate-500 hover:bg-white/5 hover:text-slate-200"}`}>{child.label}</Link>)}</div>}</div>)}</nav>}
function NavLink({item,pathname,onNavigate}:{item:NavItem;pathname:string;onNavigate?:()=>void}){const Icon=item.icon,active=item.href==="/finance"?pathname.startsWith("/finance"):pathname.startsWith(item.href);return <Link onClick={onNavigate} href={item.href} className={`mb-1 flex min-h-10 items-center gap-3 rounded-lg px-3 py-2 text-sm font-semibold transition ${active?"bg-blue-600 text-white shadow-md shadow-blue-950/30":"text-slate-400 hover:bg-white/[.06] hover:text-white"}`}>{Icon&&<Icon size={17}/>}<span>{item.label}</span>{active&&<span className="ml-auto h-1.5 w-1.5 rounded-full bg-blue-200"/>}</Link>}
function Brand({close}:{close?:()=>void}){return <div className="relative border-b border-white/8 px-3 py-2"><Link href="/dashboard" onClick={close} className="relative flex h-24 items-center justify-center overflow-hidden rounded-xl" aria-label="MK Digital Systems paneli"><Image src="/brand/mk-logo.png" alt="MK Digital Systems" width={1024} height={1024} priority className="h-44 w-44 max-w-none object-contain"/></Link>{close&&<button type="button" onClick={close} className="absolute right-3 top-3 grid h-9 w-9 place-items-center rounded-lg bg-[#071126]/80 text-slate-300 backdrop-blur hover:bg-white/10" aria-label="Menüyü kapat"><X size={19}/></button>}</div>}
function SignOut(){const router=useRouter(),[pending,setPending]=useState(false);async function run(){if(pending)return;setPending(true);const {error}=await createClient().auth.signOut();if(error){toast.error("Çıkış yapılamadı. Lütfen tekrar deneyin.");setPending(false);return}router.replace("/login");router.refresh()}return <div className="border-t border-white/8 p-3"><button type="button" onClick={run} disabled={pending} className="flex min-h-10 w-full items-center gap-3 rounded-lg px-3 py-2 text-xs font-semibold text-slate-500 transition hover:bg-white/5 hover:text-white disabled:opacity-60">{pending?<Loader2 className="animate-spin" size={16}/>:<LogOut size={16}/>} {pending?"Çıkış yapılıyor...":"Güvenli çıkış"}</button></div>}
export function Sidebar(){const pathname=usePathname();return <aside className="fixed inset-y-0 left-0 z-20 hidden w-60 flex-col border-r border-white/5 bg-[#071126] text-white lg:flex"><Brand/><Navigation pathname={pathname}/><div className="mx-4 mb-3 rounded-lg border border-blue-500/15 bg-blue-500/[.06] p-3"><div className="text-[9px] font-bold uppercase tracking-[.16em] text-blue-300">Sistem Durumu</div><div className="mt-1.5 flex items-center gap-2 text-[11px] text-slate-400"><span className="h-1.5 w-1.5 rounded-full bg-emerald-400"/>Panel operasyonel</div></div><SignOut/></aside>}
function MobileDrawer({open,close}:{open:boolean;close:()=>void}){const pathname=usePathname();useEffect(()=>{if(!open)return;const key=(event:KeyboardEvent)=>event.key==="Escape"&&close();document.addEventListener("keydown",key);document.body.style.overflow="hidden";return()=>{document.removeEventListener("keydown",key);document.body.style.overflow=""}},[open,close]);if(!open)return null;return <div className="fixed inset-0 z-50 lg:hidden"><button className="absolute inset-0 bg-slate-950/70 backdrop-blur-sm" onClick={close} aria-label="Menüyü kapat"/><aside className="relative flex h-full w-[84%] max-w-xs flex-col bg-[#071126] text-white shadow-2xl"><Brand close={close}/><Navigation pathname={pathname} onNavigate={close}/><SignOut/></aside></div>}
export function Header({title,description}:{title:string;description?:string}){const pathname=usePathname(),[menuOpen,setMenuOpen]=useState(false),[profile,setProfile]=useState({initials:"MK",avatarUrl:""}),projectMatch=pathname.match(/^\/projects\/([^/]+)$/);useEffect(()=>{let active=true;createClient().auth.getUser().then(({data:{user}})=>{if(!active||!user)return;const metadata=user.user_metadata||{},fullName=typeof metadata.full_name==="string"?metadata.full_name:typeof metadata.name==="string"?metadata.name:"",initials=fullName.trim().split(/\s+/).slice(0,2).map((part:string)=>part[0]).join("").toLocaleUpperCase("tr-TR")||"MK",candidate=typeof metadata.avatar_url==="string"?metadata.avatar_url:typeof metadata.picture==="string"?metadata.picture:"",avatarUrl=/^https?:\/\//i.test(candidate)?candidate:"";setProfile({initials,avatarUrl})});return()=>{active=false}},[]);return <><header className="sticky top-0 z-10 flex min-h-16 items-center justify-between gap-3 border-b border-slate-200/90 bg-[#f5f7fa]/90 px-4 backdrop-blur-xl sm:px-5 lg:px-6"><div className="flex min-w-0 items-center gap-3"><button type="button" onClick={()=>setMenuOpen(true)} className="btn min-h-10 shrink-0 px-3 lg:hidden" aria-label="Menüyü aç" aria-expanded={menuOpen}><Menu size={18}/></button><div className="min-w-0"><h1 className="truncate text-lg font-black tracking-tight text-slate-950">{title}</h1>{description&&<p className="mt-0.5 hidden truncate text-xs text-slate-500 sm:block">{description}</p>}</div></div><div className="flex shrink-0 items-center gap-2">{projectMatch&&<Link href={`/projects/${projectMatch[1]}/edit`} className="btn hidden sm:inline-flex">Projeyi düzenle</Link>}<Link href="/settings" title="Profil ve hesap ayarları" aria-label="Profil ve hesap ayarlarını aç" className="grid h-10 w-10 place-items-center overflow-hidden rounded-full border-2 border-white bg-[#0b1630] bg-cover bg-center text-[11px] font-black text-white shadow-sm ring-1 ring-slate-200 transition hover:ring-2 hover:ring-blue-500" style={profile.avatarUrl?{backgroundImage:`url(${JSON.stringify(profile.avatarUrl).slice(1,-1)})`}:undefined}>{profile.avatarUrl?<span className="sr-only">Profil fotoğrafı</span>:profile.initials}</Link></div></header><MobileDrawer open={menuOpen} close={()=>setMenuOpen(false)}/></>}
