"use client";
/* eslint-disable @next/next/no-img-element */
import {useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {ArrowDown,ArrowUp,Camera,ChevronLeft,ChevronRight,FileDown,ImageIcon,Pencil,Plus,ReceiptText,Trash2,X} from "lucide-react";
import {toast} from "sonner";
import {createClient} from "@/lib/supabase/client";
import {money} from "@/lib/utils";
import type {WorkAdvance,WorkExpense} from "@/lib/work-advance";
import {addWorkReceipts,deleteWorkAdvance,deleteWorkExpense,deleteWorkReceipt,saveWorkAdvance,saveWorkExpense} from "@/app/work-advance-actions";

const trDate=(date:string)=>new Date(`${date}T12:00:00`).toLocaleDateString("tr-TR");
const today=()=>new Date().toISOString().slice(0,10);
const monthLabel=(month:string)=>new Date(`${month}-01T12:00:00`).toLocaleDateString("tr-TR",{month:"long",year:"numeric"});
const shiftMonth=(month:string,delta:number)=>{const [y,m]=month.split("-").map(Number);return new Date(Date.UTC(y,m-1+delta,1)).toISOString().slice(0,7)};

export function WorkAdvanceDashboard({month,advances,expenses}:{month:string;advances:WorkAdvance[];expenses:WorkExpense[]}){
  const router=useRouter(),[dialog,setDialog]=useState<"advance"|"expense"|"expense-edit"|"detail"|null>(null),[editAdvance,setEditAdvance]=useState<WorkAdvance|null>(null),[editExpense,setEditExpense]=useState<WorkExpense|null>(null);
  const totalAdvance=advances.reduce((sum,x)=>sum+Number(x.amount),0),totalExpense=expenses.reduce((sum,x)=>sum+Number(x.amount),0);
  const movements=[...advances.map(x=>({id:x.id,date:x.advance_date,title:x.description||"İş avansı",amount:Number(x.amount),kind:"advance" as const})),...expenses.map(x=>({id:x.id,date:x.expense_date,title:x.description,amount:Number(x.amount),kind:"expense" as const}))].sort((a,b)=>b.date.localeCompare(a.date));
  const go=(value:string)=>router.push(`/work-advance?month=${value}`);
  const openAdvance=(item?:WorkAdvance)=>{setEditAdvance(item||null);setDialog("advance")},openExpense=(item?:WorkExpense)=>{setEditExpense(item||null);setDialog(item?"detail":"expense")};
  return <>
    <div className="space-y-5 p-4 sm:p-5 lg:p-8">
      <div className="card flex items-center justify-between p-2 sm:mx-auto sm:max-w-sm"><button className="btn min-h-11 px-3" onClick={()=>go(shiftMonth(month,-1))} aria-label="Önceki ay"><ChevronLeft size={20}/></button><label className="text-center text-sm font-bold capitalize"><span className="block text-xs font-normal muted">Rapor dönemi</span>{monthLabel(month)}<input className="sr-only" type="month" value={month} onChange={e=>go(e.target.value)}/></label><button className="btn min-h-11 px-3" onClick={()=>go(shiftMonth(month,1))} aria-label="Sonraki ay"><ChevronRight size={20}/></button></div>
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-3"><SummaryCard label="Toplam Alınan Avans" value={totalAdvance} tone="blue" icon={<ArrowUp/>}/><SummaryCard label="Toplam Harcama" value={totalExpense} tone="red" icon={<ArrowDown/>}/><div className="col-span-2 lg:col-span-1"><SummaryCard label="Kalan Avans" value={totalAdvance-totalExpense} tone={totalAdvance-totalExpense>=0?"green":"red"} icon={<ReceiptText/>}/></div></div>
      <div className="grid grid-cols-2 gap-3"><button className="btn btn-primary min-h-12 justify-center" onClick={()=>openAdvance()}><Plus size={18}/>Avans Ekle</button><button className="btn min-h-12 justify-center border-red-200 text-red-700" onClick={()=>openExpense()}><Plus size={18}/>Harcama Ekle</button></div>
      <button className="btn min-h-12 w-full justify-center border-emerald-200 text-emerald-700" onClick={()=>createReport(month,advances,expenses)}><FileDown size={18}/>Aylık Rapor Oluştur</button>
      <section className="card overflow-hidden"><div className="border-b p-4"><h2 className="font-bold">Son Hareketler</h2><p className="mt-1 text-xs muted">En yeni işlemler üstte gösterilir.</p></div>{movements.length?<div className="divide-y">{movements.map(item=><button type="button" onClick={()=>item.kind==="expense"&&openExpense(expenses.find(x=>x.id===item.id))} className="flex w-full items-center gap-3 p-4 text-left hover:bg-slate-50" key={`${item.kind}-${item.id}`}><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${item.kind==="advance"?"bg-blue-50 text-blue-600":"bg-red-50 text-red-600"}`}>{item.kind==="advance"?<ArrowUp size={18}/>:<ArrowDown size={18}/>}</span><span className="min-w-0 flex-1"><b className="block truncate text-sm">{item.title}</b><span className="text-xs muted">{trDate(item.date)}</span></span><b className={item.kind==="advance"?"text-blue-600":"text-red-600"}>{item.kind==="advance"?"+":"-"}{money(item.amount)}</b>{item.kind==="advance"&&<button type="button" className="p-2 muted" aria-label="Avansı düzenle" onClick={e=>{e.stopPropagation();openAdvance(advances.find(x=>x.id===item.id))}}><Pencil size={16}/></button>}</button>)}</div>:<div className="p-10 text-center text-sm muted">Bu ay henüz hareket yok.</div>}</section>
    </div>
    {dialog==="advance"&&<AdvanceModal item={editAdvance} close={()=>setDialog(null)}/>} 
    {dialog==="expense"&&<ExpenseModal close={()=>setDialog(null)}/>} 
    {dialog==="detail"&&editExpense&&<ExpenseDetail item={editExpense} close={()=>setDialog(null)} edit={()=>setDialog("expense-edit")}/>} 
    {dialog==="expense-edit"&&editExpense&&<ExpenseModal item={editExpense} close={()=>setDialog(null)}/>} 
  </>;
}

function SummaryCard({label,value,tone,icon}:{label:string;value:number;tone:"blue"|"red"|"green";icon:React.ReactNode}){const colors={blue:"bg-blue-50 text-blue-600",red:"bg-red-50 text-red-600",green:"bg-emerald-50 text-emerald-600"};return <div className="card h-full p-4"><span className={`mb-4 grid h-9 w-9 place-items-center rounded-lg ${colors[tone]}`}>{icon}</span><div className="text-lg font-bold sm:text-xl">{money(value)}</div><div className="mt-1 text-xs muted sm:text-sm">{label}</div></div>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 flex items-end bg-slate-950/50 sm:items-center sm:justify-center" onMouseDown={e=>e.target===e.currentTarget&&close()}><section className="max-h-[92vh] w-full overflow-y-auto rounded-t-2xl bg-white sm:max-w-lg sm:rounded-2xl"><header className="sticky top-0 z-10 flex items-center justify-between border-b bg-white p-4"><h2 className="font-bold">{title}</h2><button className="btn p-2" onClick={close} aria-label="Kapat"><X size={18}/></button></header>{children}</section></div>}
function AdvanceModal({item,close}:{item:WorkAdvance|null;close:()=>void}){const [pending,start]=useTransition();return <Modal title={item?"Avansı Düzenle":"Avans Ekle"} close={close}><form className="space-y-4 p-4" action={fd=>start(async()=>{try{await saveWorkAdvance(fd);toast.success("Avans kaydedildi");close()}catch(e){toast.error(e instanceof Error?e.message:"Kayıt başarısız")}})}>{item&&<input type="hidden" name="id" value={item.id}/>}<Field label="Tarih"><input required name="date" type="date" defaultValue={item?.advance_date||today()} className="field min-h-12"/></Field><Field label="Tutar"><input required name="amount" type="number" inputMode="decimal" min="0.01" step="0.01" defaultValue={item?.amount} className="field min-h-14 text-xl font-bold" placeholder="0,00"/></Field><Field label="Açıklama / Not"><textarea name="description" defaultValue={item?.description||""} className="field min-h-24"/></Field><button disabled={pending} className="btn btn-primary min-h-12 w-full justify-center">{pending?"Kaydediliyor...":"Kaydet"}</button></form>{item&&<DeleteForm action={deleteWorkAdvance} id={item.id} label="Avansı Sil" close={close}/>}</Modal>}
function ExpenseModal({item,close}:{item?:WorkExpense;close:()=>void}){const [files,setFiles]=useState<File[]>([]),[pending,start]=useTransition(),router=useRouter();return <Modal title={item?"Harcamayı Düzenle":"Harcama Ekle"} close={close}><form className="space-y-4 p-4" action={fd=>start(async()=>{try{const expenseId=await saveWorkExpense(fd);if(files.length)await uploadReceipts(expenseId,files);toast.success("Harcama kaydedildi");router.refresh();close()}catch(e){toast.error(e instanceof Error?e.message:"Kayıt başarısız")}})}>{item&&<input type="hidden" name="id" value={item.id}/>}<Field label="Tarih"><input required name="date" type="date" defaultValue={item?.expense_date||today()} className="field min-h-12"/></Field><Field label="Açıklama"><input required name="description" defaultValue={item?.description} className="field min-h-12" placeholder="Örn. Ekip öğle yemeği"/></Field><Field label="Tutar"><input required name="amount" type="number" inputMode="decimal" min="0.01" step="0.01" defaultValue={item?.amount} className="field min-h-14 text-xl font-bold" placeholder="0,00"/></Field><Field label="Fiş / Belge (isteğe bağlı)"><label className="flex min-h-24 cursor-pointer flex-col items-center justify-center rounded-xl border-2 border-dashed border-slate-300 text-sm muted"><Camera className="mb-2"/><span>Fotoğraf çek veya galeriden seç</span><span className="mt-1 text-xs">Birden fazla görsel seçebilirsiniz</span><input type="file" accept="image/*" capture="environment" multiple className="sr-only" onChange={e=>setFiles(Array.from(e.target.files||[]))}/></label>{files.length>0&&<div className="mt-2 text-xs text-emerald-700">{files.length} belge seçildi</div>}</Field><button disabled={pending} className="btn btn-primary min-h-12 w-full justify-center">{pending?"Kaydediliyor...":"Kaydet"}</button></form></Modal>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm font-medium">{label}<span className="mt-2 block">{children}</span></label>}
function DeleteForm({action,id,label,close}:{action:(fd:FormData)=>Promise<void>;id:string;label:string;close:()=>void}){const [pending,start]=useTransition();return <form className="border-t p-4" action={fd=>{if(!confirm("Bu kayıt kalıcı olarak silinsin mi?"))return;start(async()=>{try{await action(fd);toast.success("Kayıt silindi");close()}catch(e){toast.error(e instanceof Error?e.message:"Silinemedi")}})}}><input type="hidden" name="id" value={id}/><button disabled={pending} className="btn min-h-11 w-full justify-center border-red-200 text-red-600"><Trash2 size={17}/>{label}</button></form>}
function ExpenseDetail({item,close,edit}:{item:WorkExpense;close:()=>void;edit:()=>void}){const [preview,setPreview]=useState<string|null>(null),router=useRouter();return <Modal title="Harcama Detayı" close={close}><div className="space-y-4 p-4"><div className="grid grid-cols-2 gap-3"><Info label="Tarih" value={trDate(item.expense_date)}/><Info label="Tutar" value={money(Number(item.amount))}/></div><Info label="Açıklama" value={item.description}/><div><h3 className="mb-2 text-sm font-bold">Fişler / Belgeler</h3>{item.work_advance_receipts.length?<div className="grid grid-cols-2 gap-2">{item.work_advance_receipts.map(receipt=><div className="relative" key={receipt.id}><button className="block w-full" onClick={()=>receipt.url&&setPreview(receipt.url)}>{receipt.url&&<img src={receipt.url} alt="Fiş görseli" className="h-40 w-full rounded-lg border object-cover"/>}</button><button className="absolute right-2 top-2 rounded-full bg-white p-2 text-red-600 shadow" aria-label="Fişi sil" onClick={async()=>{if(confirm("Bu fiş silinsin mi?")){await deleteWorkReceipt(receipt.id);router.refresh();close()}}}><Trash2 size={15}/></button></div>)}</div>:<div className="flex items-center gap-2 rounded-lg bg-slate-50 p-3 text-sm muted"><ImageIcon size={17}/>Fiş Yok</div>}</div><button className="btn min-h-11 w-full justify-center" onClick={edit}><Pencil size={17}/>Düzenle</button></div><DeleteForm action={deleteWorkExpense} id={item.id} label="Harcamayı Sil" close={close}/>{preview&&<button className="fixed inset-0 z-[60] grid place-items-center bg-black/90 p-4" onClick={()=>setPreview(null)}><img src={preview} alt="Büyük fiş görseli" className="max-h-full max-w-full object-contain"/></button>}</Modal>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-lg bg-slate-50 p-3"><div className="text-xs muted">{label}</div><div className="mt-1 font-bold">{value}</div></div>}

async function optimize(file:File){const bitmap=await createImageBitmap(file),max=1600,scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext("2d")!.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return await new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error("Görsel işlenemedi")),"image/jpeg",.82));}
async function uploadReceipts(expenseId:string,files:File[]){const supabase=createClient(),{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Oturum gerekli");const paths:string[]=[];for(const file of files){const blob=await optimize(file),path=`${user.id}/${expenseId}/${crypto.randomUUID()}.jpg`,{error}=await supabase.storage.from("work-advance-receipts").upload(path,blob,{contentType:"image/jpeg"});if(error)throw new Error(error.message);paths.push(path)}try{await addWorkReceipts(expenseId,paths)}catch(error){await supabase.storage.from("work-advance-receipts").remove(paths);throw error}}

async function createReport(month:string,advances:WorkAdvance[],expenses:WorkExpense[]){try{const {jsPDF}=await import("jspdf"),doc=new jsPDF(),totalAdvance=advances.reduce((s,x)=>s+Number(x.amount),0),totalExpense=expenses.reduce((s,x)=>s+Number(x.amount),0);let y=18;doc.setFont("helvetica","bold");doc.setFontSize(16);doc.text("MUSTAFA ONER",105,y,{align:"center"});y+=8;doc.text("IS AVANSI HARCAMA DOKUMU",105,y,{align:"center"});y+=9;doc.setFontSize(12);doc.text(monthLabel(month).toLocaleUpperCase("tr-TR").normalize("NFD").replace(/[\u0300-\u036f]/g,""),105,y,{align:"center"});y+=13;doc.setFontSize(10);doc.text(`Toplam Alinan Avans: ${money(totalAdvance)}`,14,y);y+=6;doc.text(`Toplam Harcama: ${money(totalExpense)}`,14,y);y+=6;doc.text(`Kalan Avans: ${money(totalAdvance-totalExpense)}`,14,y);y+=12;doc.setFont("helvetica","bold");doc.text("Tarih",14,y);doc.text("Aciklama",43,y);doc.text("Tutar",196,y,{align:"right"});y+=3;doc.line(14,y,196,y);doc.setFont("helvetica","normal");for(const expense of expenses){y+=7;if(y>275){doc.addPage();y=18}doc.text(trDate(expense.expense_date),14,y);doc.text(doc.splitTextToSize(expense.description,105)[0],43,y);doc.text(money(Number(expense.amount)),196,y,{align:"right"})}y+=10;doc.setFont("helvetica","bold");doc.text(`TOPLAM HARCAMA: ${money(totalExpense)}`,196,y,{align:"right"});doc.addPage();y=18;doc.setFontSize(15);doc.text("FISLER / BELGELER",14,y);for(const expense of expenses){if(y>245){doc.addPage();y=18}y+=10;doc.setFontSize(10);doc.text(`${trDate(expense.expense_date)} - ${expense.description} - ${money(Number(expense.amount))}`,14,y);if(!expense.work_advance_receipts.length){y+=7;doc.setFont("helvetica","normal");doc.text("Fis / belge eklenmedi",18,y);continue}for(const receipt of expense.work_advance_receipts){if(!receipt.url)continue;const data=await imageData(receipt.url);if(y>170){doc.addPage();y=18}y+=5;doc.addImage(data,"JPEG",18,y,174,100,undefined,"FAST");y+=106}}const blob=doc.output("blob"),file=new File([blob],`is-avansi-${month}.pdf`,{type:"application/pdf"});if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({title:"İş Avansı Harcama Dökümü",files:[file]})}else doc.save(file.name)}catch(error){if((error as DOMException)?.name!=="AbortError")toast.error(error instanceof Error?error.message:"PDF oluşturulamadı")}}
async function imageData(url:string){const blob=await fetch(url).then(r=>r.blob());return await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(blob)})}
