import {Header} from "@/components/sidebar";
import {getFinance} from "@/lib/finance";
import {MonthPicker,FinanceNav,FinanceForm,CategoryManager,Records,DonutChart} from "@/components/finance";
import {money} from "@/lib/utils";

export default async function Page({searchParams}:{searchParams:Promise<{month?:string}>}){
 const {month}=await searchParams,{range,expenses,categories,accounts}=await getFinance(month);
 const totals=Object.entries(expenses.reduce<Record<string,number>>((result,expense)=>{const category=expense.finance_categories?.name||"Kategorisiz";result[category]=(result[category]||0)+Number(expense.amount);return result},{})).sort((a,b)=>b[1]-a[1]);
 return <><Header title="Giderler" description="Aylık harcamaları kategori bazında yönetin."/><div className="space-y-5 p-5 lg:p-8"><div className="flex flex-wrap justify-between gap-4"><FinanceNav/><MonthPicker value={range.value} path="/finance/expenses"/></div><div className="grid gap-5 xl:grid-cols-2"><FinanceForm kind="expense" categories={categories} accounts={accounts}/><CategoryManager categories={categories}/></div><div className="grid gap-5 xl:grid-cols-2"><section className="card"><h2 className="border-b p-5 font-bold">Kategori Bazlı Toplamlar</h2>{totals.length?<div className="divide-y">{totals.map(([name,total])=>{const categoryExpenses=expenses.filter(expense=>(expense.finance_categories?.name||"Kategorisiz")===name);return <details key={name} className="group"><summary className="flex cursor-pointer list-none items-center justify-between p-3 text-sm hover:bg-slate-50"><span className="font-medium group-open:text-blue-600">{name}</span><b>{money(total)}</b></summary><div className="divide-y border-t bg-slate-50/70 px-3">{categoryExpenses.map(expense=><div key={expense.id} className="flex items-center justify-between gap-3 py-2 text-xs"><div><span>{new Date(`${expense.expense_date}T12:00:00`).toLocaleDateString("tr-TR")}</span>{expense.description&&<span className="ml-1 muted">({expense.description})</span>}</div><b>{money(Number(expense.amount))}</b></div>)}</div></details>})}</div>:<div className="p-10 text-center text-sm muted">Bu ay gider kaydı bulunmuyor.</div>}</section><section className="card"><h2 className="border-b p-5 font-bold">Aylık Gider Dağılımı</h2><DonutChart items={totals.map(([name,value])=>({name,value}))} emptyText="Bu ay gider dağılımı bulunmuyor."/></section></div><Records kind="expense" items={expenses} categories={categories} accounts={accounts}/></div></>
}
